### ISSUE TITLE
Is Disqus good for prototype?

### ISSUE THREAD

**Issue by krigersergei** [krigersergei/accessible-components#6]
## Disqus

To save time I decided to use https://disqus.com for adding comments.
Will it be enough for a prototype?

@Menelion could you please test it with a screen reader and give some feedback?

**Comment by Menelion** [comment]
@krigersergei I did give you some feedback on the Accordion page just for testing it :), but to reiterate: no, it wouldn't go, unfortunately. They are experiencing some severe accessibility problems both in their text editor and in controls around (they are reported as "HTML Object", at least in chrome with JAWS).  
I'm pretty sure that, at least for an average blind user, it would be near to impossible to post a simple comment, sorry.

**Comment by beqabeqa473** [comment]
hello.

agree with @Menelion 

first of all, blind user won't be able to explore page with arrow keys at least with nvda in chrome.
focus is jumping when pressing down arrow near the multiline editbox.

i don't know if it is an issue but anyway, it would be good to include text as aria-label rather than in title attribute.

these object HTMLElements what was said by @Menelion are elements to bold underline ad so on. but yes, for a normal blind user this would be not an easy task t odo.

ps: thank you @krigersergei for such efforts.

**Comment by krigersergei** [comment]
@Menelion @beqabeqa473 thanks for your feedback, seems that we can't use it.
